### ISSUE TITLE
The Giving Block integration 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#160]
Integrating the Giving Blocks API requires
- [x] Giveth/impact-graph#155
- [x] Giveth/impact-graph#156
- [x] Giveth/impact-graph#157
- [x] Giveth/impact-graph#158
- [x] Giveth/impact-graph#159

**Comment by CarlosQ96** [comment]
Related Issue: https://github.com/Giveth/giveth-next/issues/117
API documentation for the GivingBlocks: https://the-giving-block.gitbook.io/public-api-documentation/endpoints-documentation
The Endpoints that will be used:
1. Login and Refresh endpoints for authenticated requests.
2. GetOrganizationsList endpoint to retrieve the logo and title and Scrape the description of the giving blocks website.
3. CreateDepositAddress For getting a single address that we will use as the main in the project in giveth.io. 

https://thegivingblock.com/donate/Save-The-Children/ Example url. The slug structure for scraping.

The process as I was working on it would run once and create all the projects in our DB.
We have to decide if we are updating periodically or not. What happens if someone updates the project on the adminbro?
@mohammadranjbarz @MoeNick

**Comment by mohammadranjbarz** [comment]
> Related Issue: [Giveth/giveth-next#117](https://github.com/Giveth/giveth-next/issues/117) API documentation for the GivingBlocks: https://the-giving-block.gitbook.io/public-api-documentation/endpoints-documentation The Endpoints that will be used:
> 
> 1. Login and Refresh endpoints for authenticated requests.
> 2. GetOrganizationsList endpoint to retrieve the logo and title and Scrape the description of the giving blocks website.
> 3. CreateDepositAddress For getting a single address that we will use as the main in the project in giveth.io.
> 
> https://thegivingblock.com/donate/Save-The-Children/ Example url. The slug structure for scraping.
> 
> The process as I was working on it would run once and create all the projects in our DB. We have to decide if we are updating periodically or not. What happens if someone updates the project on the adminbro? @mohammadranjbarz @MoeNick

Thanks @CarlosQ96 , very good data 
@MoeNick this all that Carlos and I know about giving block, And Thanks to Carlos you can see it here

**Comment by CarlosQ96** [comment]
@MoeNick @WhyldWanderer Two questions I have:
1. Should I create the wallet address as anonymous so I don't set up a lot of user information (address, email, zip, city, etc) when creating it.
Endpoint: https://the-giving-block.gitbook.io/public-api-documentation/endpoints-documentation#createdepositaddress
2. Who should I set as the admin of the exported projects?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
It's on staging

(because the staging ENV of givingblocks just had one project, We have set the production URLs of givingblocks in our staging then you can see lots of their projects in our staging ENV, but if you think it's not ok, its totally reversible, we can change the URLs in config and delete all imported projects from staging DB

**Comment by MoeNick** [comment]
Awesome, thanks

**Comment by divine-comedian** [comment]
what does a successful test of this issue look like?

**Comment by divine-comedian** [comment]
updates on how to test please @mohammadranjbarz  @CarlosQ96

**Comment by CarlosQ96** [comment]
Basically we have the project exported, we can list/unlist, unverify, add hearts, etc. In staging we could not test donations because we had mainnet addresses.
This projects are on production and I think Ashley is testing the donation flow. But per other testing with Griff it should work. @divine-comedian

**Comment by divine-comedian** [comment]
@WhyldWanderer  you have the admin bro dashboard credentials for production - do you want to test this flow? Is there any email associated with them that might get hit with spam when testing these actions?

**Comment by WhyldWanderer** [comment]
The email is the same for all projects.. Griff and I have the credentials so we can test each of the admin dashboard functions without spamming anyone. 

Ive been waiting with fingers crossed to hear back from the person in charge of Keep A Breast Foundation so that we can test live donations, however I haven't heard anything as of yet.

Can you think of any ways that we could test donations without being in touch with the organizations themselves? We do not have contact info for these projects - they are not available due to Giving Block privacy agreements. Griff tested sending different tokens all to the same address (his gemini account) but im not sure if this is sufficient testing to be firmly confident in the functionality.

**Comment by CarlosQ96** [comment]
This is done, Ashley, Griff and me tested with a giving blocks project.
