### ISSUE TITLE
Security Analysis

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#257]
- [x] is there a reason we've got access-control-allow-origin: set to * in some places?
- [x] I would recommend setting X-Frame-Options: DENY or X-Frame-Options: SAMEORIGIN to prevent clickjacking (unless you expect to be hosted in a frame on another site, in which case I have a different suggestion)
- [x] It would be nice to suppress the "X-Powered-By: Next.js" header
- [ ] You might wanna consider stripping comments before launch
- [x] Would you be ok with adding "Strict-Transport-Security: max-age=10000; includeSubDomains; preload" in order to force all assets to load over HTTPS

**Comment by geleeroyale** [comment]
ok - I solved these:
- It would be nice to suppress the "X-Powered-By: Next.js" header (by setting a value in next.config)
- Would you be ok with adding "Strict-Transport-Security: max-age=10000; includeSubDomains; preload" in order to force all assets to load over HTTPS (by setting it in impact-graph nginx)

this needs clarification:
- I would recommend setting X-Frame-Options: DENY or X-Frame-Options: SAMEORIGIN to prevent clickjacking (unless you expect to be hosted in a frame on another site, in which case I have a different suggestion)

I did set x-frame-options: deny on the backend, but of course the frontend can still be loaded via iframe ... can we somehow deny on the frontend as well, or is it sufficient to do it on the backend?

**Comment by aminlatifi** [comment]
Created #259 PR to fix the first one
