### ISSUE TITLE
Setting up Authentication Service

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#514]
New Authentication Service is implemented by @CarlosQ96 
Now it's time to:

- [x]  Deploy Service on kubernetese https://github.com/Giveth/SiweAuthMicroservice/issues/1
- [x] Define a separate route and API for authentication (like giveth.io/v1/auth) on Gateway
- [x] Develop frontend to use the new service https://github.com/Giveth/giveth-dapps-v2/issues/701
- [x] Develop impact-graph to use the new Authentication Service to verify issues JWT #515

**Comment by divine-comedian** [comment]
@aminlatifi  is this epic still relevant or can it be closed?
