### ISSUE TITLE
Backend changes for support QF

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#980]
We should add new entity for qfRound

# Entity changes

## qfRound entity

| name          | type    | required | description                                                                                           |
|---------------|---------|----------|-------------------------------------------------------------------------------------------------------|
| name          | string  | yes      | can have name or something like round1, round2, ...                                                   |
| beginDate     | Date    | yes      |                                                                                                       |
| endDate       | Date    | yes      |                                                                                                       |
| active        | boolean | yes      |                                                                                                       |
| allocatedFund | integer | no       | With knowing how much allocated to this round we can estimate project's share for showing in frontend |
| createdAt     | Date    | yes      |                                                                                                       |

## project entity changes
We just need to add a boolean named `qfEligible` and if it's true, we will know this project is assigned to active qfRound and it's enough for us

## donation entity change
We should add
* `qfRound`: We fill this with active qfRound, if project that we donate on that is assigned to current active qfRound otherwise it will be empty
* `donorPassportScore`: We fill this with donor's passportScore if `qfRound` is filled and also we might update this field in the end of the qfRound

# Endpoints
* We need an endpoint to return projects related to current active qfRound
* Get donation details and estimated fund share for the project

# Others
* We need to have a function, that get projectId, then return the allocated qfRound fund to this project based on donations and donorScores to this project
* will need to have a function that considers the amount donated to a particular project & the number of donors... and compares it to the amounts donated & number of donors on every other project... and then returns some values for "estimated matching". These numbers should update every x period of time... so that they stay up-to-date as more people donate.
* We need a function that get a qfRound number as input, and updates all donorScores of the donations that are related to this qfRound
* We need to add a button in admin panel on project page to add/remove that project to current active qfRound
* We should can edit qfRound in admin panel

**Comment by MoeNick** [comment]
I have these in my mind that may have some changes on your ideas:

- List of donations by QF and the impact they made. 
- Authentication of createDonation validation by Scorer (Gitcoin0

our regular donations is sending some token to another address and their validation is easy, let's review the QF donations. where they go? don't they go to a smart contact if so, the verification may change.

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz for preparing this,

In my view, we must reconsider project<>qfRound relation. As I know, a project will be participated in qfRound or not. So it can be only a true/false flag instead of a many-to-many relation with qfRound entity.
I mean, we can only have that flag in projects, and at the end of a round, do the calculation with donations to projects with this flag true and qfRound number matches. 

Also, I think we can fill the qfRound number in all donations happening in a qfRound, regardless of their project status

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz for preparing this,
> 
> In my view, we must reconsider project<>qfRound relation. As I know, a project will be participated in qfRound or not. So it can be only a true/false flag instead of a many-to-many relation with qfRound entity. I mean, we can only have that flag in projects, and at the end of a round, do the calculation with donations to projects with this flag true and qfRound number matches.
> 
> Also, I think we can fill the qfRound number in all donations happening in a qfRound, regardless of their project status

You know I was thinking we might  need to know in the future that in qfRound 2 what projects we had or what projects we had in qfRound 3 so if need the history we need something like many to many relationship, but if we just need  projects of current active qfRound, a boolean flag is enough

@laurenluz  @MoeNick  WDYT?

**Comment by mohammadranjbarz** [comment]
> I have these in my mind that may have some changes on your ideas:
> 
> * List of donations by QF and the impact they made.
> * Authentication of createDonation validation by Scorer (Gitcoin0
> 
> our regular donations is sending some token to another address and their validation is easy, let's review the QF donations. where they go? don't they go to a smart contact if so, the verification may change.

I thought the donation flow is the same, but if a project is qf eligible, we need to add something in backend for that donation, something like donorPassportScore, .. but the createDonation endpoint doesn't need any change

**Comment by MoeNick** [comment]
> 

Yeah @mohammadranjbarz  seems the business is I have a regular project and enters different QF round, one after the other, and when the round is closed, I get back to my ordinary situation. Correct me @laurenluz if Im wrong.

**Comment by MoeNick** [comment]
- Donations Table in a single project page (owner view and single view) 
- Donations total amount (in cart/ in single project page)
- Toral Donation user made (in my account)
I wonder how we can handle them in a round, after the round and when the round is closed. 
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> * Donations Table in a single project page (owner view and single view)
> * Donations total amount (in cart/ in single project page)
> * Toral Donation user made (in my account)
>   I wonder how we can handle them in a round, after the round and when the round is closed.
>   @mohammadranjbarz

As I said above we can store qfRound to donation when we create donation, so we would have the exact qfRounds of projects for all donations, so in that case we can query for all donations to a project in qfRound 2 or in qfRound 3, we can easily achieve it

**Comment by MoeNick** [comment]
Good job @mohammadranjbarz thanks

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  JFYI to stay in the loop

**Comment by laurenluz** [comment]
@MoeNick @mohammadranjbarz @aminlatifi

### QF round true/false or complex tracking

Projects - when they are in an active QF round - will have a slightly different project single page and project card (that shows the QF round, estimated matching etc.) When the round ends, they will go back to "normal". However... for the donation table on the project single page, we should show if a donation was done in QFround1, QFround2, etc. The reason is, because when we send the matching funds... we will want to show also that like for example, $1000 was given to this project as a result of the donations they got in QFround 1.

I think we could do a true/false to say if the project is in a QF round or not... but we would also need someway of checking which donations were part of *which* QF round... and which were not part of any QF round. So perhaps we need to have the more complicated tracking.

### How donations are handled

The donations will still be our regular peer-to-peer style. We're not building any contracts in between to handle donations for QF.

### Estimated matching card

I'm not sure that this was considered in the original design for the backend - tell me if so?

I think we will need to have a function that considers the amount donated to a particular project & the number of donors... and compares it to the amounts donated & number of donors on every other project... and then returns some values for "estimated matching". These numbers should update every x period of time... so that they stay up-to-date as more people donate.

We should fork what gitcoin did this in the original grants protocol. Somewhere [here](https://github.com/gitcoinco/web/tree/master/app/grants) @mohammadranjbarz 

![image](https://github.com/Giveth/impact-graph/assets/75490971/7a56a039-41d6-4888-b6a2-58c776408699)

**Comment by mohammadranjbarz** [comment]
> We should add new entity for qfRound
> 
> # Entity changes
> ## qfRound entity
> name	type	required	description
> name	string	yes	can have name or something like round1, round2, ...
> beginDate	Date	yes	
> endDate	Date	yes	
> active	boolean	yes	
> allocatedFund	integer	no	With knowing how much allocated to this round we can estimate project's share for showing in frontend
> createdAt	Date	yes	
> ## project entity changes
> We just need to add a boolean named `qfEligible` and if it's true, we will know this project is assigned to active qfRound and it's enough for us
> 
> ## donation entity change
> We should add
> 
> * `qfRound`: We fill this with active qfRound, if project that we donate on that is assigned to current active qfRound otherwise it will be empty
> * `donorPassportScore`: We fill this with donor's passportScore if `qfRound` is filled and also we might update this field in the end of the qfRound
> 
> # Endpoints
> * We need an endpoint to return projects related to current active qfRound
> * Get donation details and estimated fund share for the project
> 
> # Others
> * We need to have a function, that get projectId, then return the allocated qfRound fund to this project based on donations and donorScores to this project
> * We need a function that get a qfRound number as input, and updates all donorScores of the donations that are related to this qfRound
> * We need to add a button in admin panel on project page to add/remove that project to current active qfRound
> * We should can edit qfRound in admin panel

Thanks @laurenluz  for your information

@aminlatifi  @MoeNick  with information that Lauren put in the comments, I changed this and removed many to many relation between project entity and qfRound, now a boolean flag is enough and also it makes it easier

**Comment by laurenluz** [comment]
@mohammadranjbarz - and after a round ends, we will be able to query our database to find out which projects were in QF round 1, or which where in QF round 2, which were in any QF round ever, etc.?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - and after a round ends, we will be able to query our database to find out which projects were in QF round 1, or which where in QF round 2, which were in any QF round ever, etc.?

If we just use boolean flag it's hard to track these types of reports

**Comment by laurenluz** [comment]
hmm... we will be including a label in the donation table which shows which QF round a donation was made in. And Mo was going to add a filter option on the donation table so you could filter by QF round. is that going to be possible with the current system? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> hmm... we will be including a label in the donation table which shows which QF round a donation was made in. And Mo was going to add a filter option on the donation table so you could filter by QF round. is that going to be possible with the current system? @mohammadranjbarz

@laurenluz  Yeah sure, we will support it

**Comment by mohammadranjbarz** [comment]
I implemented below tasks in #986 PR and deployed it on develop env https://dev.serve.giveth.io
- [x] #997 you can get list of qfRounds with 
```
query{
 qfRounds {
     id
     name
     isActive
 }
}
```
- [x] #994  You can pass `qfRoundId` in `allProjects` query to filter projects 
axios sample:
```
    const result = await axios.post(graphqlUrl, {
      query: fetchMultiFilterAllProjectsQuery,
      variables: {
        qfRoundId: qfRound.id,
      },
    });
```

- [x] #998 As you see in below picture I added 2 buttons to add/remove projects to active qfRound
**Add To Qf Round** and **Remove From Qf Round** buttons
<img width="1119" alt="Screen Shot 1402-03-02 at 16 14 18" src="https://github.com/Giveth/impact-graph/assets/9850545/103cc720-51ac-4462-9cdc-6fecf296215a">


And I show list qfRounds of projects in project detail page in adminjs panel

<img width="1176" alt="Screen Shot 1402-03-02 at 16 26 06" src="https://github.com/Giveth/impact-graph/assets/9850545/ba857f3a-9e04-4fd8-8dc7-77d0aa5c5010">


- [x] #995  You can add below codes to `projectBySlug` query to get project's related qfRounds
```
  qfRounds {
          name
          isActive
          id
        }
```

- [x] #1007 I added another filter named `ActiveQfRound` to get projects related to active qfRound
Axios code sample:

```
    const result = await axios.post(graphqlUrl, {
      query: fetchMultiFilterAllProjectsQuery,
      variables: {
        limit: 50,
        skip: 0,
        filters: ['ActiveQfRound'],
      },
    });
```

**PS** 
@laurenluz  @MoeNick  @MohammadPCh  I assume we would not have more than 1 active qfRound at same time, and now I created a qfRound, so during testing don't create more active qfRounds

**Comment by laurenluz** [comment]
@mohammadranjbarz just FYI the way gitcoin does it.. they sometimes do have different rounds active at once. Like they had a climate round, an OSS round, a Eth infrastructure round...

For our MVP, we will definitely have only one round, but in the future we may want to scale up and run different rounds simultaneously.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz just FYI the way gitcoin does it.. they sometimes do have different rounds active at once. Like they had a climate round, an OSS round, a Eth infrastructure round...
> 
> For our MVP, we will definitely have only one round, but in the future we may want to scale up and run different rounds simultaneously.

So for now we are cool, but for supporting multiple active  qfRound at same time we need to change two things in future:
1. Adminjs panel for adding project to active qfRound it would not work correctly if we have multiple active qfRound
2. Filter by activeQfRound will return all projects related to all active qfRounds although I guess it's ok

**Comment by laurenluz** [comment]
I think it will be nice to be able to add a filter by x round.

Because in this case, we may have multiple different matching pools - one for each round.. so people will want to donate to projects according to which round they are in.

For the MVP, it is ok as it is... but if QF is successful, we will need to build that functionality eventually.

**Comment by maryjaf** [comment]
If a project doesn't have one of the criteria for adding to QF such as verified status
when a admin user try to add this project to QF, he should got an error ? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> I think it will be nice to be able to add a filter by x round.
> 
> Because in this case, we may have multiple different matching pools - one for each round.. so people will want to donate to projects according to which round they are in.
> 
> For the MVP, it is ok as it is... but if QF is successful, we will need to build that functionality eventually.

We have that as well, now we have two types of filters:
1. send `qfRoundId` and we return projects related to `qfRound`
2. just send `activeQfRound` that return projects that connected to an active`qfRound`

the first item is what you are saying

**Comment by laurenluz** [comment]
GREAT

**Comment by laurenluz** [comment]
@MohammadPCh
